# Odoo yaml template for travis-ci
# # __version__=0.2.1
#

language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

git:
  submodules: false

addons:
  apt:
#    sources:
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev
      - python-lxml

before_install:
  - export TRAVIS_DEBUG_MODE="1"
# Use Zeroincombenze(R) tools
  - git clone https://github.com/zeroincombenze/tools.git ${HOME}/tools --single-branch --depth=1
  - mv ${HOME}/tools/maintainer-quality-tools ${HOME}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

install:
  - travis_install_env
  # tests of document_ftp and delivery fail. The following two are excluded because they depend on delivery
  # account_invoice_sequential_dates fails with FatturaPA 
  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery,account_invoice_sequential_dates
  # - export INSTALL_OPTIONS="--without-demo=account"
  # - cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .
  # - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="0"
  - TESTS="0" ODOO_REPO="odoo/odoo"
  - TESTS="0" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="zeroincombenze/OCB"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
